### ISSUE TITLE
Not a valid JAR

### ISSUE THREAD

**Issue by eliasah** [mehikmat/BigSchool#1]
I can't run the hadoop command. It says that the JAR is not valid. Have you encountered such a problem? Can you help me fix it please?

**Comment by mehikmat** [comment]
Let me check

**Comment by eliasah** [comment]
I fixed it and I edited the README.md in case of an error. But Now I found another issue. I think it's also a path problem. 
![capture decran 2014-04-04 a 11 02 16](https://cloud.githubusercontent.com/assets/2973143/2613508/e54c53fc-bbd7-11e3-94fe-f4932615529b.png)

**Comment by mehikmat** [comment]
I have fixed this problem. Please get updates.

**Comment by eliasah** [comment]
Ok thanks but now we have another issue. I'll open a new post for it
