### ISSUE TITLE
Exception in thread "main" org.apache.hadoop.mapred.InvalidInputException: Input path does not exist

### ISSUE THREAD

**Issue by eliasah** [mehikmat/BigSchool#3]
Hadoop can't find com.bigschool.drive.App

**Comment by mehikmat** [comment]
Please get updates, I have resolved this issue.

**Comment by eliasah** [comment]
I did get the updates but it still doesn't solve the issue.
![capture decran 2014-04-04 a 11 33 45](https://cloud.githubusercontent.com/assets/2973143/2613802/48f6147a-bbdc-11e3-8503-d3c9dca61f53.png)

**Comment by mehikmat** [comment]
Did you do mvn clean package

**Comment by eliasah** [comment]
I fixed it. I'm on MacOSX. Maybe it doesn't like the class path that you were giving it.

**Comment by mehikmat** [comment]
Yes may be since I had tested it only in Linux system

**Comment by eliasah** [comment]
Sorry, doesn't work

**Comment by mehikmat** [comment]
@eliasah I think even it didn't work in your system, good solution
shouldn't be the one that you are trying and that I were approaching
before. According java doc and maven We don't need to specify the main
class if you specify main class in pom file

what do you think?

**Comment by eliasah** [comment]
The only issue is that some doc say that you have to specify it and other say the opposite...

**Comment by mehikmat** [comment]
I think It's better to not specify Main class. Maven automatically
generates menifest file and java detects main class by looking into it.
